# This workflow will do a clean install of node dependencies, build the source code and run eslint and tests

name: Lint and Test

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master

env:
  NODE_VERSION: '15'

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run lint

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run test
